#!/usr/bin/env python3
"""Single entry point to reproduce all tables and figures from the paper.

Usage:
    python code/run_replication.py              # run everything
    python code/run_replication.py --tables      # tables only
    python code/run_replication.py --figures      # figures only
    python code/run_replication.py --skip-slow    # skip heavy conditional model zoo
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

os.environ.setdefault("MPLBACKEND", "Agg")

REPO_ROOT = Path(__file__).resolve().parents[1]
ANALYSIS_DIR = REPO_ROOT / "code" / "analysis"

TABLE_SCRIPTS = [
    ("Unconditional strategy returns (Tables 1a–1e)", "option_strats_uncond_analysis.py"),
    ("Implementable PNL diagnostics (Table 2)", "compute_implementable_pnl.py"),
    ("Tail risk diagnostics (Table 3)", "compute_tail_risk_diagnostics.py"),
    ("Clustered inference + MHT (Table 4)", "compute_clustered_inference_mht.py"),
    ("Structural break 2022 (Table 5)", "compute_structural_break_2022.py"),
    ("VIX regime conditioning (Table 6)", "compute_vix_regime_conditioning.py"),
    ("Conditional OOS protocol (Table 7)", "compute_conditional_oos_protocol.py"),
    ("Moneyness selection (Appendix)", "moneyness_selection.py"),
]

SLOW_SCRIPTS = {"compute_conditional_model_zoo.py"}

# These require upstream model-zoo CSV outputs generated by the full pipeline.
# Run separately after compute_conditional_model_zoo.py produces its outputs.
PIPELINE_SCRIPTS = [
    ("Conditional model zoo (Tables 8–9)", "compute_conditional_model_zoo.py"),
    ("Target choice comparison", "build_conditional_target_choice_table.py"),
    ("Binary decision summary", "derive_binary_decision_summary.py"),
]

FIGURE_SCRIPTS = [
    ("Strategy payoffs, bar charts, time series", "figs_strats.py"),
    ("Conditional OOS investment TS (prereq for top-K figure)", "compute_conditional_oos_investment_ts.py"),
    ("Top-K basket leg composition", "plot_conditional_topk_basket_legs.py"),
]


def run_script(name: str, script: str, cwd: Path) -> bool:
    print(f"\n{'─' * 60}")
    print(f"  {name}")
    print(f"  → {script}")
    print(f"{'─' * 60}")
    t0 = time.time()
    result = subprocess.run(
        [sys.executable, str(cwd / script)],
        cwd=str(cwd),
        capture_output=False,
    )
    elapsed = time.time() - t0
    if result.returncode == 0:
        print(f"  ✓ done in {elapsed:.1f}s")
        return True
    else:
        print(f"  ✗ FAILED (exit code {result.returncode}) after {elapsed:.1f}s")
        return False


def main() -> None:
    parser = argparse.ArgumentParser(description="Reproduce all paper exhibits.")
    parser.add_argument("--tables", action="store_true", help="Run table scripts only")
    parser.add_argument("--figures", action="store_true", help="Run figure scripts only")
    parser.add_argument("--skip-slow", action="store_true", help="Skip heavy scripts (model zoo)")
    parser.add_argument("--full-pipeline", action="store_true",
                        help="Also run pipeline-dependent scripts (model zoo, investment TS, etc.)")
    args = parser.parse_args()

    run_tables = not args.figures
    run_figures = not args.tables

    scripts: list[tuple[str, str]] = []
    if run_tables:
        for name, script in TABLE_SCRIPTS:
            if args.skip_slow and script in SLOW_SCRIPTS:
                print(f"  [skip-slow] Skipping {script}")
                continue
            scripts.append((name, script))
        if args.full_pipeline:
            for name, script in PIPELINE_SCRIPTS:
                if args.skip_slow and script in SLOW_SCRIPTS:
                    print(f"  [skip-slow] Skipping {script}")
                    continue
                scripts.append((name, script))
    if run_figures:
        scripts.extend(FIGURE_SCRIPTS)

    print("=" * 60)
    print("0DTE Replication — Reproducing Paper Exhibits")
    print(f"  Scripts to run: {len(scripts)}")
    print(f"  Output: {REPO_ROOT / 'output'}")
    print("=" * 60)

    t_start = time.time()
    results = []
    for name, script in scripts:
        ok = run_script(name, script, ANALYSIS_DIR)
        results.append((name, script, ok))

    elapsed_total = time.time() - t_start
    n_ok = sum(1 for *_, ok in results if ok)
    n_fail = len(results) - n_ok

    print("\n" + "=" * 60)
    print(f"Replication complete: {n_ok} passed, {n_fail} failed, {elapsed_total:.0f}s total")
    if n_fail:
        print("\nFailed scripts:")
        for name, script, ok in results:
            if not ok:
                print(f"  ✗ {script}: {name}")
    print("=" * 60)

    sys.exit(0 if n_fail == 0 else 1)


if __name__ == "__main__":
    main()
